apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-api-replica
  labels:
    app : my-api-replica
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-api-replica
  template:
    metadata:
      labels:
        app: my-api-replica
    spec:
      containers:
      - name: my-api-replica
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080
        env:
        - name: PING_LISTEN_PORT 
          value : "8080"